param(
    [Parameter(Mandatory = $true)]
    [string]$SourceRoot
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

# Bootstrap the material-release verifier set from an immutable helper commit, then
# delegate to the previously native-Windows-certified repair wrapper from that same
# commit. The reconstructed source manifest is regenerated by the delegated wrapper,
# so every restored tool becomes part of the exact source identity before builds/tests.
$carrierCommit = 'd46a92633debde94ed3a805bc2571af0ccaeb451'
$carrierRoot = "https://raw.githubusercontent.com/sohweiyu2023/CloudScribe-Pro/$carrierCommit/.cloudscribe-ci"
$toolNames = @(
    'verify_dotnet_sdk_version.py',
    'verify_project_dependencies.py',
    'verify_repository.py',
    'verify_stage1_source.py',
    'verify_stage2_source.py',
    'verify_stage2_evidence_inventory.py',
    'run_python_regression_shards.py',
    'create_source_archive.py',
    'verify_source_release.py'
)
$toolsDirectory = Join-Path $SourceRoot 'tools'
New-Item -ItemType Directory -Path $toolsDirectory -Force | Out-Null
foreach ($name in $toolNames) {
    $destination = Join-Path $toolsDirectory $name
    Invoke-WebRequest -Uri "$carrierRoot/material-tools/$name" -OutFile $destination
    if (-not (Test-Path -LiteralPath $destination -PathType Leaf) -or (Get-Item -LiteralPath $destination).Length -le 0) {
        throw "Material verifier download failed or was empty: $name"
    }
}

$compileArguments = @('-m','py_compile') + @($toolNames | ForEach-Object { Join-Path $toolsDirectory $_ })
& python @compileArguments
if ($LASTEXITCODE -ne 0) { throw "Restored material verifier syntax validation failed: $LASTEXITCODE" }
Write-Host "Restored and syntax-checked $($toolNames.Count) material/release verifiers from immutable commit $carrierCommit."

$coreWrapper = Join-Path $env:RUNNER_TEMP 'cloudscribe-048-certified-core-wrapper.ps1'
Invoke-WebRequest -Uri "$carrierRoot/invoke-cloudscribe-048-certification.ps1" -OutFile $coreWrapper
if (-not (Test-Path -LiteralPath $coreWrapper -PathType Leaf) -or (Get-Item -LiteralPath $coreWrapper).Length -le 0) {
    throw 'Certified core wrapper download failed or was empty.'
}

& pwsh -NoProfile -File $coreWrapper -SourceRoot $SourceRoot
if ($LASTEXITCODE -ne 0) {
    throw "Certified core wrapper failed with exit code $LASTEXITCODE."
}
